FROM node:20-alpine

WORKDIR /app

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

RUN npm i -g serve

EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
